const std = @import("std");
const builtin = @import("builtin");
const c = @import("c.zig");
const wwise_options = @import("wwise_options");

pub const WwiseError = error{
    NotImplemented,
    Fail,
    PartialSuccess,
    NotCompatible,
    AlreadyConnected,
    InvalidFile,
    AudioFileHeaderTooLarge,
    MaxReached,
    InvalidID,
    IDNotFound,
    InvalidInstanceID,
    NoMoreData,
    InvalidStateGroup,
    ChildAlreadyHasAParent,
    InvalidLanguage,
    CannotAddItseflAsAChild,
    InvalidParameter,
    ElementAlreadyInList,
    PathNotFound,
    PathNoVertices,
    PathNotRunning,
    PathNotPaused,
    PathNodeAlreadyInList,
    PathNodeNotInList,
    DataNeeded,
    NoDataNeeded,
    DataReady,
    NoDataReady,
    InsufficientMemory,
    Cancelled,
    UnknownBankID,
    BankReadError,
    InvalidSwitchType,
    FormatNotReady,
    WrongBankVersion,
    FileNotFound,
    DeviceNotReady,
    BankAlreadyLoaded,
    RenderedFX,
    ProcessNeeded,
    ProcessDone,
    MemManagerNotInitialized,
    StreamMgrNotInitialized,
    SSEInstructionsNotSupported,
    Busy,
    UnsupportedChannelConfig,
    PluginMediaNotAvailable,
    MustBeVirtualized,
    CommandTooLarge,
    RejectedByFilter,
    InvalidCustomPlatformName,
    DLLCannotLoad,
    DLLPathNotFound,
    NoJavaVM,
    OpenSLError,
    PluginNotRegistered,
    DataAlignmentError,
    DeviceNotCompatible,
    DuplicateUniqueID,
    InitBankNotLoaded,
    DeviceNotFound,
    PlayingIDNotFound,
    InvalidFloatValue,
    FileFormatMismatch,
    NoDistinctListener,
    ACP_Error,
    ResourceInUse,
    InvalidBankType,
    AlreadyInitialized,
    NotInitialized,
    FilePermissionError,
    UnknownFileError,
};

pub fn handleAkResult(result: c.WWISEC_AKRESULT) WwiseError!void {
    return switch (result) {
        c.WWISEC_AK_NotImplemented => return WwiseError.NotImplemented,
        c.WWISEC_AK_Success => return,
        c.WWISEC_AK_Fail => return WwiseError.Fail,
        c.WWISEC_AK_PartialSuccess => return WwiseError.PartialSuccess,
        c.WWISEC_AK_NotCompatible => return WwiseError.NotCompatible,
        c.WWISEC_AK_AlreadyConnected => return WwiseError.AlreadyConnected,
        c.WWISEC_AK_InvalidFile => return WwiseError.InvalidFile,
        c.WWISEC_AK_AudioFileHeaderTooLarge => return WwiseError.AudioFileHeaderTooLarge,
        c.WWISEC_AK_MaxReached => return WwiseError.MaxReached,
        c.WWISEC_AK_InvalidID => return WwiseError.InvalidID,
        c.WWISEC_AK_IDNotFound => return WwiseError.IDNotFound,
        c.WWISEC_AK_InvalidInstanceID => return WwiseError.InvalidInstanceID,
        c.WWISEC_AK_NoMoreData => return WwiseError.NoMoreData,
        c.WWISEC_AK_InvalidStateGroup => return WwiseError.InvalidStateGroup,
        c.WWISEC_AK_ChildAlreadyHasAParent => return WwiseError.ChildAlreadyHasAParent,
        c.WWISEC_AK_InvalidLanguage => return WwiseError.InvalidLanguage,
        c.WWISEC_AK_CannotAddItseflAsAChild => return WwiseError.CannotAddItseflAsAChild,
        c.WWISEC_AK_InvalidParameter => return WwiseError.InvalidParameter,
        c.WWISEC_AK_ElementAlreadyInList => return WwiseError.ElementAlreadyInList,
        c.WWISEC_AK_PathNotFound => return WwiseError.PathNotFound,
        c.WWISEC_AK_PathNoVertices => return WwiseError.PathNoVertices,
        c.WWISEC_AK_PathNotRunning => return WwiseError.PathNotRunning,
        c.WWISEC_AK_PathNotPaused => return WwiseError.PathNotPaused,
        c.WWISEC_AK_PathNodeAlreadyInList => return WwiseError.PathNodeAlreadyInList,
        c.WWISEC_AK_PathNodeNotInList => return WwiseError.PathNodeNotInList,
        c.WWISEC_AK_DataNeeded => return WwiseError.DataNeeded,
        c.WWISEC_AK_NoDataNeeded => return WwiseError.NoDataNeeded,
        c.WWISEC_AK_DataReady => return WwiseError.DataReady,
        c.WWISEC_AK_NoDataReady => return WwiseError.NoDataReady,
        c.WWISEC_AK_InsufficientMemory => return WwiseError.InsufficientMemory,
        c.WWISEC_AK_Cancelled => return WwiseError.Cancelled,
        c.WWISEC_AK_UnknownBankID => return WwiseError.UnknownBankID,
        c.WWISEC_AK_BankReadError => return WwiseError.BankReadError,
        c.WWISEC_AK_InvalidSwitchType => return WwiseError.InvalidSwitchType,
        c.WWISEC_AK_FormatNotReady => return WwiseError.FormatNotReady,
        c.WWISEC_AK_WrongBankVersion => return WwiseError.WrongBankVersion,
        c.WWISEC_AK_FileNotFound => return WwiseError.FileNotFound,
        c.WWISEC_AK_DeviceNotReady => return WwiseError.DeviceNotReady,
        c.WWISEC_AK_BankAlreadyLoaded => return WwiseError.BankAlreadyLoaded,
        c.WWISEC_AK_RenderedFX => return WwiseError.RenderedFX,
        c.WWISEC_AK_ProcessNeeded => return WwiseError.ProcessNeeded,
        c.WWISEC_AK_ProcessDone => return WwiseError.ProcessDone,
        c.WWISEC_AK_MemManagerNotInitialized => return WwiseError.MemManagerNotInitialized,
        c.WWISEC_AK_StreamMgrNotInitialized => return WwiseError.StreamMgrNotInitialized,
        c.WWISEC_AK_SSEInstructionsNotSupported => return WwiseError.SSEInstructionsNotSupported,
        c.WWISEC_AK_Busy => return WwiseError.Busy,
        c.WWISEC_AK_UnsupportedChannelConfig => return WwiseError.UnsupportedChannelConfig,
        c.WWISEC_AK_PluginMediaNotAvailable => return WwiseError.PluginMediaNotAvailable,
        c.WWISEC_AK_MustBeVirtualized => return WwiseError.MustBeVirtualized,
        c.WWISEC_AK_CommandTooLarge => return WwiseError.CommandTooLarge,
        c.WWISEC_AK_RejectedByFilter => return WwiseError.RejectedByFilter,
        c.WWISEC_AK_InvalidCustomPlatformName => return WwiseError.InvalidCustomPlatformName,
        c.WWISEC_AK_DLLCannotLoad => return WwiseError.DLLCannotLoad,
        c.WWISEC_AK_DLLPathNotFound => return WwiseError.DLLPathNotFound,
        c.WWISEC_AK_NoJavaVM => return WwiseError.NoJavaVM,
        c.WWISEC_AK_OpenSLError => return WwiseError.OpenSLError,
        c.WWISEC_AK_PluginNotRegistered => return WwiseError.PluginNotRegistered,
        c.WWISEC_AK_DataAlignmentError => return WwiseError.DataAlignmentError,
        c.WWISEC_AK_DeviceNotCompatible => return WwiseError.DeviceNotCompatible,
        c.WWISEC_AK_DuplicateUniqueID => return WwiseError.DuplicateUniqueID,
        c.WWISEC_AK_InitBankNotLoaded => return WwiseError.InitBankNotLoaded,
        c.WWISEC_AK_DeviceNotFound => return WwiseError.DeviceNotFound,
        c.WWISEC_AK_PlayingIDNotFound => return WwiseError.PlayingIDNotFound,
        c.WWISEC_AK_InvalidFloatValue => return WwiseError.InvalidFloatValue,
        c.WWISEC_AK_FileFormatMismatch => return WwiseError.FileFormatMismatch,
        c.WWISEC_AK_NoDistinctListener => return WwiseError.NoDistinctListener,
        c.WWISEC_AK_ACP_Error => return WwiseError.ACP_Error,
        c.WWISEC_AK_ResourceInUse => return WwiseError.ResourceInUse,
        c.WWISEC_AK_InvalidBankType => return WwiseError.InvalidBankType,
        c.WWISEC_AK_AlreadyInitialized => return WwiseError.AlreadyInitialized,
        c.WWISEC_AK_NotInitialized => return WwiseError.NotInitialized,
        c.WWISEC_AK_FilePermissionError => return WwiseError.FilePermissionError,
        c.WWISEC_AK_UnknownFileError => return WwiseError.UnknownFileError,
        else => return WwiseError.NotImplemented,
    };
}

pub const toOSChar = blk: {
    if (builtin.os.tag == .windows) {
        break :blk toOSCharUtf16;
    } else {
        break :blk toCString;
    }
};

pub fn toOSCharUtf16(allocator: std.mem.Allocator, value: []const u8) ![:0]u16 {
    return std.unicode.utf8ToUtf16LeWithNull(allocator, value);
}

pub fn toCString(allocator: std.mem.Allocator, value: []const u8) ![:0]u8 {
    return std.cstr.addNullByte(allocator, value);
}

pub fn osCharAllocator(fallback_allocator: std.mem.Allocator) std.heap.StackFallbackAllocator(wwise_options.string_stack_size) {
    return std.heap.stackFallback(wwise_options.string_stack_size, fallback_allocator);
}
