const c = @import("wwise_c");

pub const AK_INVALID_PLUGINID = c.AK_INVALID_PLUGINID;
pub const AK_INVALID_SHARE_SET_ID = c.AK_INVALID_SHARE_SET_ID;
pub const AK_INVALID_GAME_OBJECT = c.AK_INVALID_GAME_OBJECT;
pub const AK_INVALID_UNIQUE_ID = c.AK_INVALID_UNIQUE_ID;
pub const AK_INVALID_RTPC_ID = c.AK_INVALID_RTPC_ID;
pub const AK_INVALID_PLAYING_ID = c.AK_INVALID_PLAYING_ID;
pub const AK_DEFAULT_SWITCH_STATE = c.AK_DEFAULT_SWITCH_STATE;
pub const AK_INVALID_POOL_ID = c.AK_INVALID_POOL_ID;
pub const AK_DEFAULT_POOL_ID = c.AK_DEFAULT_POOL_ID;
pub const AK_INVALID_AUX_ID = c.AK_INVALID_AUX_ID;
pub const AK_INVALID_FILE_ID = c.AK_INVALID_FILE_ID;
pub const AK_INVALID_CACHE_ID = c.AK_INVALID_CACHE_ID;
pub const AK_INVALID_DEVICE_ID = c.AK_INVALID_DEVICE_ID;
pub const AK_INVALID_BANK_ID = c.AK_INVALID_BANK_ID;
pub const AK_FALLBACK_ARGUMENTVALUE_ID = c.AK_FALLBACK_ARGUMENTVALUE_ID;
pub const AK_INVALID_CHANNELMASK = c.AK_INVALID_CHANNELMASK;
pub const AK_INVALID_OUTPUT_DEVICE_ID = c.AK_INVALID_OUTPUT_DEVICE_ID;
pub const AK_INVALID_PIPELINE_ID = c.AK_INVALID_PIPELINE_ID;
pub const AK_INVALID_AUDIO_OBJECT_ID = c.AK_INVALID_AUDIO_OBJECT_ID;

pub const AK_TRANSPORT_GAME_OBJECT = c.AK_TRANSPORT_GAME_OBJECT;
pub const AK_DIRECT_GAME_OBJECT = c.AK_DIRECT_GAME_OBJECT;

// Priority
pub const AK_DEFAULT_PRIORITY = c.AK_DEFAULT_PRIORITY;
pub const AK_MIN_PRIORITY = c.AK_MIN_PRIORITY;
pub const AK_MAX_PRIORITY = c.AK_MAX_PRIORITY;

// Default bank I/O settings.
pub const AK_DEFAULT_BANK_IO_PRIORITY = c.AK_DEFAULT_BANK_IO_PRIORITY;
pub const AK_DEFAULT_BANK_THROUGHPUT = c.AK_DEFAULT_BANK_THROUGHPUT;

// Bank version
pub const AK_SOUNDBANK_VERSION = c.AK_SOUNDBANK_VERSION;

// Job types
pub const AkJobType_Generic = c.AkJobType_Generic;
pub const AkJobType_AudioProcessing = c.AkJobType_AudioProcessing;
pub const AkJobType_SpatialAudio = c.AkJobType_SpatialAudio;
pub const AK_NUM_JOB_TYPES = c.AK_NUM_JOB_TYPES;

// Languages
pub const AK_MAX_LANGUAGE_NAME_SIZE = c.AK_MAX_LANGUAGE_NAME_SIZE;

// ------------------------
// File Type ID Definitions
// ------------------------

// Company ID for plugin development.
pub const AKCOMPANYID_PLUGINDEV_MIN = c.AKCOMPANYID_PLUGINDEV_MIN;
pub const AKCOMPANYID_PLUGINDEV_MAX = c.AKCOMPANYID_PLUGINDEV_MAX;

// Vendor ID
pub const AKCOMPANYID_AUDIOKINETIC = c.AKCOMPANYID_AUDIOKINETIC;
pub const AKCOMPANYID_AUDIOKINETIC_EXTERNAL = c.AKCOMPANYID_AUDIOKINETIC_EXTERNAL;
pub const AKCOMPANYID_MCDSP = c.AKCOMPANYID_MCDSP;
pub const AKCOMPANYID_WAVEARTS = c.AKCOMPANYID_WAVEARTS;
pub const AKCOMPANYID_PHONETICARTS = c.AKCOMPANYID_PHONETICARTS;
pub const AKCOMPANYID_IZOTOPE = c.AKCOMPANYID_IZOTOPE;
pub const AKCOMPANYID_CRANKCASEAUDIO = c.AKCOMPANYID_CRANKCASEAUDIO;
pub const AKCOMPANYID_IOSONO = c.AKCOMPANYID_IOSONO;
pub const AKCOMPANYID_AUROTECHNOLOGIES = c.AKCOMPANYID_AUROTECHNOLOGIES;
pub const AKCOMPANYID_DOLBY = c.AKCOMPANYID_DOLBY;
pub const AKCOMPANYID_TWOBIGEARS = c.AKCOMPANYID_TWOBIGEARS;
pub const AKCOMPANYID_OCULUS = c.AKCOMPANYID_OCULUS;
pub const AKCOMPANYID_BLUERIPPLESOUND = c.AKCOMPANYID_BLUERIPPLESOUND;
pub const AKCOMPANYID_ENZIEN = c.AKCOMPANYID_ENZIEN;
pub const AKCOMPANYID_KROTOS = c.AKCOMPANYID_KROTOS;
pub const AKCOMPANYID_NURULIZE = c.AKCOMPANYID_NURULIZE;
pub const AKCOMPANYID_SUPERPOWERED = c.AKCOMPANYID_SUPERPOWERED;
pub const AKCOMPANYID_GOOGLE = c.AKCOMPANYID_GOOGLE;
pub const AKCOMPANYID_VISISONICS = c.AKCOMPANYID_VISISONICS;

// File/encoding types of Audiokinetic.
pub const AKCODECID_BANK = c.AKCODECID_BANK;
pub const AKCODECID_PCM = c.AKCODECID_PCM;
pub const AKCODECID_ADPCM = c.AKCODECID_ADPCM;
pub const AKCODECID_XMA = c.AKCODECID_XMA;
pub const AKCODECID_VORBIS = c.AKCODECID_VORBIS;
pub const AKCODECID_WIIADPCM = c.AKCODECID_WIIADPCM;
pub const AKCODECID_PCM_WAV = c.AKCODECID_PCM_WAV;
pub const AKCODECID_EXTERNAL_SOURCE = c.AKCODECID_EXTERNAL_SOURCE;
pub const AKCODECID_XWMA = c.AKCODECID_XWMA;
pub const AKCODECID_FILE_PACKAGE = c.AKCODECID_FILE_PACKAGE;
pub const AKCODECID_ATRAC9 = c.AKCODECID_ATRAC9;
pub const AKCODECID_VAG = c.AKCODECID_VAG;
pub const AKCODECID_PROFILERCAPTURE = c.AKCODECID_PROFILERCAPTURE;
pub const AKCODECID_ANALYSISFILE = c.AKCODECID_ANALYSISFILE;
pub const AKCODECID_MIDI = c.AKCODECID_MIDI;
pub const AKCODECID_OPUSNX = c.AKCODECID_OPUSNX;
pub const AKCODECID_CAF = c.AKCODECID_CAF;
pub const AKCODECID_AKOPUS = c.AKCODECID_AKOPUS;
pub const AKCODECID_AKOPUS_WEM = c.AKCODECID_AKOPUS_WEM;
pub const AKCODECID_MEMORYMGR_DUMP = c.AKCODECID_MEMORYMGR_DUMP;
pub const AKCODECID_SONY360 = c.AKCODECID_SONY360;

pub const AKCODECID_BANK_EVENT = c.AKCODECID_BANK_EVENT;
pub const AKCODECID_BANK_BUS = c.AKCODECID_BANK_BUS;

pub const AKPLUGINID_RECORDER = c.AKPLUGINID_RECORDER;
pub const AKPLUGINID_IMPACTER = c.AKPLUGINID_IMPACTER;
pub const AKPLUGINID_SYSTEM_OUTPUT_META = c.AKPLUGINID_SYSTEM_OUTPUT_META;
pub const AKPLUGINID_AUDIO_OBJECT_ATTENUATION_META = c.AKPLUGINID_AUDIO_OBJECT_ATTENUATION_META;
pub const AKPLUGINID_AUDIO_OBJECT_PRIORITY_META = c.AKPLUGINID_AUDIO_OBJECT_PRIORITY_META;

pub const AKEXTENSIONID_SPATIALAUDIO = c.AKEXTENSIONID_SPATIALAUDIO;
pub const AKEXTENSIONID_INTERACTIVEMUSIC = c.AKEXTENSIONID_INTERACTIVEMUSIC;
pub const AKEXTENSIONID_MIDIDEVICEMGR = c.AKEXTENSIONID_MIDIDEVICEMGR;

// The following are internally defined
pub const AK_WAVE_FORMAT_VAG = c.AK_WAVE_FORMAT_VAG;
pub const AK_WAVE_FORMAT_AT9 = c.AK_WAVE_FORMAT_AT9;
pub const AK_WAVE_FORMAT_VORBIS = c.AK_WAVE_FORMAT_VORBIS;
pub const AK_WAVE_FORMAT_OPUSNX = c.AK_WAVE_FORMAT_OPUSNX;
pub const AK_WAVE_FORMAT_OPUS = c.AK_WAVE_FORMAT_OPUS;
pub const AK_WAVE_FORMAT_OPUS_WEM = c.AK_WAVE_FORMAT_OPUS_WEM;
pub const AK_WAVE_FORMAT_XMA2 = c.AK_WAVE_FORMAT_XMA2;

pub const AK_INVALID_SAMPLE_POS = c.AK_INVALID_SAMPLE_POS;
