const wwise_options = @import("wwise_options");

pub const AkMemSettings = MemoryMgr.AkMemSettings;
pub const Comm = if (wwise_options.use_communication) @import("Comm.zig") else void;
pub const IOHooks = @import("IOHooks.zig");
pub const JobWorkerMgr = if (wwise_options.use_default_job_worker) @import("JobWorkerMgr.zig") else void;
pub const MemoryMgr = @import("MemoryMgr.zig");
pub const Monitor = @import("Monitor.zig");
pub const MusicEngine = @import("MusicEngine.zig");
pub const SoundEngine = @import("SoundEngine.zig");
pub const SpatialAudio = if (wwise_options.use_spatial_audio) @import("SpatialAudio.zig") else void;
pub const SpeakerVolumes = @import("SpeakerVolumes.zig");
pub const StreamMgr = @import("StreamMgr.zig");
pub const TempAlloc = @import("TempAlloc.zig");

// callbacks.zig
const callbacks = @import("callbacks.zig");
pub const AkCallbackType = callbacks.AkCallbackType;
pub const AkCallbackInfo = callbacks.AkCallbackInfo;
pub const AkEventCallbackInfo = callbacks.AkEventCallbackInfo;
pub const AkMIDIEventCallbackInfo = callbacks.AkMIDIEventCallbackInfo;
pub const AkMarkerCallbackInfo = callbacks.AkMarkerCallbackInfo;
pub const AkDurationCallbackInfo = callbacks.AkDurationCallbackInfo;
pub const AkDynamicSequenceItemCallbackInfo = callbacks.AkDynamicSequenceItemCallbackInfo;
pub const AkSpeakerVolumeMatrixCallbackInfo = callbacks.AkSpeakerVolumeMatrixCallbackInfo;
pub const AkBusMeteringCallbackInfo = callbacks.AkBusMeteringCallbackInfo;
pub const AkOutputDeviceMeteringCallbackInfo = callbacks.AkOutputDeviceMeteringCallbackInfo;
pub const AkMusicPlaylistCallbackInfo = callbacks.AkMusicPlaylistCallbackInfo;
pub const AkSegmentInfo = callbacks.AkSegmentInfo;
pub const AkMusicSyncCallbackInfo = callbacks.AkMusicSyncCallbackInfo;
pub const AkResourceMonitorDataSummary = callbacks.AkResourceMonitorDataSummary;
pub const AkCallbackFunc = callbacks.AkCallbackFunc;
pub const AkBusCallbackFunc = callbacks.AkBusCallbackFunc;
pub const AkBusMeteringCallbackFunc = callbacks.AkBusMeteringCallbackFunc;
pub const AkOutputDeviceMeteringCallbackFunc = callbacks.AkOutputDeviceMeteringCallbackFunc;
pub const AkBankCallbackFunc = callbacks.AkBankCallbackFunc;
pub const AkGlobalCallbackLocation = callbacks.AkGlobalCallbackLocation;
pub const AkGlobalCallbackFunc = callbacks.AkGlobalCallbackFunc;
pub const AkResourceMonitorCallbackFunc = callbacks.AkResourceMonitorCallbackFunc;
pub const AkAudioDeviceEvent = callbacks.AkAudioDeviceEvent;
pub const AkDeviceStatusCallbackFunc = callbacks.AkDeviceStatusCallbackFunc;
pub const AkCaptureCallbackFunc = callbacks.AkCaptureCallbackFunc;

// common.zig
const common = @import("common.zig");
pub const AkOSChar = common.AkOSChar;
pub const AkUtf16 = common.AkUtf16;
pub const AkUniqueID = common.AkUniqueID;
pub const AkStateID = common.AkStateID;
pub const AkStateGroupID = common.AkStateGroupID;
pub const AkPlayingID = common.AkPlayingID;
pub const AkTimeMs = common.AkTimeMs;
pub const AkPortNumber = common.AkPortNumber;
pub const AkPitchValue = common.AkPitchValue;
pub const AkVolumeValue = common.AkVolumeValue;
pub const AkGameObjectID = common.AkGameObjectID;
pub const AkLPFType = common.AkLPFType;
pub const AkMemPoolId = common.AkMemPoolId;
pub const AkPluginID = common.AkPluginID;
pub const AkCodecID = common.AkCodecID;
pub const AkAuxBusID = common.AkAuxBusID;
pub const AkPluginParamID = common.AkPluginParamID;
pub const AkPriority = common.AkPriority;
pub const AkDataCompID = common.AkDataCompID;
pub const AkDataTypeID = common.AkDataTypeID;
pub const AkDataInterleaveID = common.AkDataInterleaveID;
pub const AkSwitchGroupID = common.AkSwitchGroupID;
pub const AkSwitchStateID = common.AkSwitchStateID;
pub const AkRtpcID = common.AkRtpcID;
pub const AkRtpcValue = common.AkRtpcValue;
pub const AkBankID = common.AkBankID;
pub const AkFileID = common.AkFileID;
pub const AkDeviceID = common.AkDeviceID;
pub const AkTriggerID = common.AkTriggerID;
pub const AkArgumentValueID = common.AkArgumentValueID;
pub const AkChannelMask = common.AkChannelMask;
pub const AkModulatorID = common.AkModulatorID;
pub const AkAcousticTextureID = common.AkAcousticTextureID;
pub const AkImageSourceID = common.AkImageSourceID;
pub const AkOutputDeviceID = common.AkOutputDeviceID;
pub const AkPipelineID = common.AkPipelineID;
pub const AkRayID = common.AkRayID;
pub const AkAudioObjectID = common.AkAudioObjectID;
pub const AkJobType = common.AkJobType;
pub const AkJobType_Generic = common.AkJobType_Generic;
pub const AkJobType_AudioProcessing = common.AkJobType_AudioProcessing;
pub const AkJobType_SpatialAudio = common.AkJobType_SpatialAudio;
pub const AK_INVALID_PLUGINID = common.AK_INVALID_PLUGINID;
pub const AK_INVALID_SHARE_SET_ID = common.AK_INVALID_SHARE_SET_ID;
pub const AK_INVALID_GAME_OBJECT = common.AK_INVALID_GAME_OBJECT;
pub const AK_INVALID_UNIQUE_ID = common.AK_INVALID_UNIQUE_ID;
pub const AK_INVALID_RTPC_ID = common.AK_INVALID_RTPC_ID;
pub const AK_INVALID_PLAYING_ID = common.AK_INVALID_PLAYING_ID;
pub const AK_DEFAULT_SWITCH_STATE = common.AK_DEFAULT_SWITCH_STATE;
pub const AK_INVALID_POOL_ID = common.AK_INVALID_POOL_ID;
pub const AK_DEFAULT_POOL_ID = common.AK_DEFAULT_POOL_ID;
pub const AK_INVALID_AUX_ID = common.AK_INVALID_AUX_ID;
pub const AK_INVALID_FILE_ID = common.AK_INVALID_FILE_ID;
pub const AK_INVALID_DEVICE_ID = common.AK_INVALID_DEVICE_ID;
pub const AK_INVALID_BANK_ID = common.AK_INVALID_BANK_ID;
pub const AK_FALLBACK_ARGUMENTVALUE_ID = common.AK_FALLBACK_ARGUMENTVALUE_ID;
pub const AK_INVALID_CHANNELMASK = common.AK_INVALID_CHANNELMASK;
pub const AK_INVALID_OUTPUT_DEVICE_ID = common.AK_INVALID_OUTPUT_DEVICE_ID;
pub const AK_INVALID_PIPELINE_ID = common.AK_INVALID_PIPELINE_ID;
pub const AK_INVALID_AUDIO_OBJECT_ID = common.AK_INVALID_AUDIO_OBJECT_ID;
pub const AK_DEFAULT_PRIORITY = common.AK_DEFAULT_PRIORITY;
pub const AK_MIN_PRIORITY = common.AK_MIN_PRIORITY;
pub const AK_MAX_PRIORITY = common.AK_MAX_PRIORITY;
pub const AK_DEFAULT_BANK_IO_PRIORITY = common.AK_DEFAULT_BANK_IO_PRIORITY;
pub const AK_DEFAULT_BANK_THROUGHPUT = common.AK_DEFAULT_BANK_THROUGHPUT;
pub const AK_SOUNDBANK_VERSION = common.AK_SOUNDBANK_VERSION;
pub const AK_NUM_JOB_TYPES = common.AK_NUM_JOB_TYPES;
pub const AK_MAX_PATH = common.AK_MAX_PATH;
pub const AK_MAX_LANGUAGE_NAME_SIZE = common.AK_MAX_LANGUAGE_NAME_SIZE;
pub const AKCOMPANYID_PLUGINDEV_MIN = common.AKCOMPANYID_PLUGINDEV_MIN;
pub const AKCOMPANYID_PLUGINDEV_MAX = common.AKCOMPANYID_PLUGINDEV_MAX;
pub const AKCOMPANYID_AUDIOKINETIC = common.AKCOMPANYID_AUDIOKINETIC;
pub const AKCOMPANYID_AUDIOKINETIC_EXTERNAL = common.AKCOMPANYID_AUDIOKINETIC_EXTERNAL;
pub const AKCOMPANYID_MCDSP = common.AKCOMPANYID_MCDSP;
pub const AKCOMPANYID_WAVEARTS = common.AKCOMPANYID_WAVEARTS;
pub const AKCOMPANYID_PHONETICARTS = common.AKCOMPANYID_PHONETICARTS;
pub const AKCOMPANYID_IZOTOPE = common.AKCOMPANYID_IZOTOPE;
pub const AKCOMPANYID_CRANKCASEAUDIO = common.AKCOMPANYID_CRANKCASEAUDIO;
pub const AKCOMPANYID_IOSONO = common.AKCOMPANYID_IOSONO;
pub const AKCOMPANYID_AUROTECHNOLOGIES = common.AKCOMPANYID_AUROTECHNOLOGIES;
pub const AKCOMPANYID_DOLBY = common.AKCOMPANYID_DOLBY;
pub const AKCOMPANYID_TWOBIGEARS = common.AKCOMPANYID_TWOBIGEARS;
pub const AKCOMPANYID_OCULUS = common.AKCOMPANYID_OCULUS;
pub const AKCOMPANYID_BLUERIPPLESOUND = common.AKCOMPANYID_BLUERIPPLESOUND;
pub const AKCOMPANYID_ENZIEN = common.AKCOMPANYID_ENZIEN;
pub const AKCOMPANYID_KROTOS = common.AKCOMPANYID_KROTOS;
pub const AKCOMPANYID_NURULIZE = common.AKCOMPANYID_NURULIZE;
pub const AKCOMPANYID_SUPERPOWERED = common.AKCOMPANYID_SUPERPOWERED;
pub const AKCOMPANYID_GOOGLE = common.AKCOMPANYID_GOOGLE;
pub const AKCOMPANYID_VISISONICS = common.AKCOMPANYID_VISISONICS;
pub const AKCODECID_BANK = common.AKCODECID_BANK;
pub const AKCODECID_PCM = common.AKCODECID_PCM;
pub const AKCODECID_ADPCM = common.AKCODECID_ADPCM;
pub const AKCODECID_XMA = common.AKCODECID_XMA;
pub const AKCODECID_VORBIS = common.AKCODECID_VORBIS;
pub const AKCODECID_WIIADPCM = common.AKCODECID_WIIADPCM;
pub const AKCODECID_PCMEX = common.AKCODECID_PCMEX;
pub const AKCODECID_EXTERNAL_SOURCE = common.AKCODECID_EXTERNAL_SOURCE;
pub const AKCODECID_XWMA = common.AKCODECID_XWMA;
pub const AKCODECID_FILE_PACKAGE = common.AKCODECID_FILE_PACKAGE;
pub const AKCODECID_ATRAC9 = common.AKCODECID_ATRAC9;
pub const AKCODECID_VAG = common.AKCODECID_VAG;
pub const AKCODECID_PROFILERCAPTURE = common.AKCODECID_PROFILERCAPTURE;
pub const AKCODECID_ANALYSISFILE = common.AKCODECID_ANALYSISFILE;
pub const AKCODECID_MIDI = common.AKCODECID_MIDI;
pub const AKCODECID_OPUSNX = common.AKCODECID_OPUSNX;
pub const AKCODECID_CAF = common.AKCODECID_CAF;
pub const AKCODECID_AKOPUS = common.AKCODECID_AKOPUS;
pub const AKCODECID_AKOPUS_WEM = common.AKCODECID_AKOPUS_WEM;
pub const AKCODECID_MEMORYMGR_DUMP = common.AKCODECID_MEMORYMGR_DUMP;
pub const AKCODECID_SONY360 = common.AKCODECID_SONY360;
pub const AKCODECID_BANK_EVENT = common.AKCODECID_BANK_EVENT;
pub const AKCODECID_BANK_BUS = common.AKCODECID_BANK_BUS;
pub const AKPLUGINID_METER = common.AKPLUGINID_METER;
pub const AKPLUGINID_RECORDER = common.AKPLUGINID_RECORDER;
pub const AKPLUGINID_IMPACTER = common.AKPLUGINID_IMPACTER;
pub const AKPLUGINID_SYSTEM_OUTPUT_META = common.AKPLUGINID_SYSTEM_OUTPUT_META;
pub const AKPLUGINID_AUDIO_OBJECT_ATTENUATION_META = common.AKPLUGINID_AUDIO_OBJECT_ATTENUATION_META;
pub const AKPLUGINID_AUDIO_OBJECT_PRIORITY_META = common.AKPLUGINID_AUDIO_OBJECT_PRIORITY_META;
pub const AKEXTENSIONID_SPATIALAUDIO = common.AKEXTENSIONID_SPATIALAUDIO;
pub const AKEXTENSIONID_INTERACTIVEMUSIC = common.AKEXTENSIONID_INTERACTIVEMUSIC;
pub const AKEXTENSIONID_MIDIDEVICEMGR = common.AKEXTENSIONID_MIDIDEVICEMGR;
pub const AK_WAVE_FORMAT_VAG = common.AK_WAVE_FORMAT_VAG;
pub const AK_WAVE_FORMAT_AT9 = common.AK_WAVE_FORMAT_AT9;
pub const AK_WAVE_FORMAT_VORBIS = common.AK_WAVE_FORMAT_VORBIS;
pub const AK_WAVE_FORMAT_OPUSNX = common.AK_WAVE_FORMAT_OPUSNX;
pub const AK_WAVE_FORMAT_OPUS = common.AK_WAVE_FORMAT_OPUS;
pub const AK_WAVE_FORMAT_OPUS_WEM = common.AK_WAVE_FORMAT_OPUS_WEM;
pub const WAVE_FORMAT_XMA2 = common.WAVE_FORMAT_XMA2;
pub const AK_BANK_PLATFORM_DATA_ALIGNMENT = common.AK_BANK_PLATFORM_DATA_ALIGNMENT;
pub const IAkSoftwareCodec = common.IAkSoftwareCodec;
pub const IAkFileCodec = common.IAkFileCodec;
pub const IAkGrainCodec = common.IAkGrainCodec;
pub const AkCreateFileSourceCallback = common.AkCreateFileSourceCallback;
pub const AkCreateBankSourceCallback = common.AkCreateBankSourceCallback;
pub const AkCreateFileCodecCallback = common.AkCreateFileCodecCallback;
pub const AkCreateGrainCodecCallback = common.AkCreateGrainCodecCallback;
pub const AkCodecDescriptor = common.AkCodecDescriptor;
pub const AkBankType = common.AkBankType;
pub const AkFileHandle = common.AkFileHandle;
pub const AkAudioDeviceState = common.AkAudioDeviceState;
pub const AkDeviceDescription = common.AkDeviceDescription;
pub const AkExternalSourceInfo = common.AkExternalSourceInfo;
pub const AkConnectionType = common.AkConnectionType;
pub const AkVector64 = common.AkVector64;
pub const AkVector = common.AkVector;
pub const AkWorldTransform = common.AkWorldTransform;
pub const AkTransform = common.AkTransform;
pub const AkSoundPosition = common.AkSoundPosition;
pub const AkListenerPosition = common.AkListenerPosition;
pub const AkObstructionOcclusionValues = common.AkObstructionOcclusionValues;
pub const AkChannelEmitter = common.AkChannelEmitter;
pub const AkEmitterListenerPair = common.AkEmitterListenerPair;
pub const AkSetPositionFlags = common.AkSetPositionFlags;
pub const AkSpeakerPanningType = common.AkSpeakerPanningType;
pub const Ak3DPositionType = common.Ak3DPositionType;
pub const AkPanningRule = common.AkPanningRule;
pub const Ak3DSpatializationMode = common.Ak3DSpatializationMode;
pub const AkMeteringFlags = common.AkMeteringFlags;
pub const AkPluginType = common.AkPluginType;
pub const AKRESULT = common.AKRESULT;
pub const AkGroupType = common.AkGroupType;
pub const AkCurveInterpolation = common.AkCurveInterpolation;
pub const AkAuxSendValue = common.AkAuxSendValue;
pub const AkAudioSettings = common.AkAudioSettings;
pub const WwiseError = common.WwiseError;
pub const handleAkResult = common.handleAkResult;
pub const fromOSChar = common.fromOSChar;
pub const toOSChar = common.toOSChar;
pub const fromOSCharUtf16 = common.fromOSCharUtf16;
pub const toOSCharUtf16 = common.toOSCharUtf16;
pub const fromCString = common.fromCString;
pub const toCString = common.toCString;
pub const stackCharAllocator = common.stackCharAllocator;
pub const DefaultEnumType = common.DefaultEnumType;

// common_defs.zig
const common_defs = @import("common_defs.zig");
pub const AK_INT = common_defs.AK_INT;
pub const AK_FLOAT = common_defs.AK_FLOAT;
pub const AkMetering = common_defs.AkMetering;
pub const Ak3DAudioSinkCapabilities = common_defs.Ak3DAudioSinkCapabilities;
pub const AkSampleType = common_defs.AkSampleType;
pub const AkAudioBuffer = common_defs.AkAudioBuffer;

// error_message_translator.zig
pub usingnamespace @import("error_message_translator.zig");
pub usingnamespace @import("IAkPlugin.zig");
pub usingnamespace @import("IAkPluginMemAlloc.zig");
pub usingnamespace @import("IAkStreamMgr.zig");
pub usingnamespace @import("IBytes.zig");
pub usingnamespace @import("midi_types.zig");
pub usingnamespace @import("platform_context.zig");
pub usingnamespace @import("settings.zig");
pub usingnamespace @import("speaker_config.zig");
pub usingnamespace @import("virtual_acoustics.zig");
pub usingnamespace @import("wwise_platform.zig");

pub const reflect_game_data = if (wwise_options.use_spatial_audio) @import("reflect_game_data.zig") else struct {};
pub const Windows = if (wwise_options.platform == .windows) @import("win_sound_engine.zig") else struct {};

comptime {
    @setEvalBranchQuota(5000);
    @import("std").testing.refAllDeclsRecursive(@This());
}
