const builtin = @import("builtin");
const c = @import("wwise_c");

// This is a mirror of AKRESULT without AK_Success
pub const WwiseError = error{
    NotImplemented,
    Fail,
    PartialSuccess,
    NotCompatible,
    AlreadyConnected,
    InvalidFile,
    AudioFileHeaderTooLarge,
    MaxReached,
    InvalidID,
    IDNotFound,
    InvalidInstanceID,
    NoMoreData,
    InvalidStateGroup,
    ChildAlreadyHasAParent,
    InvalidLanguage,
    CannotAddItselfAsAChild,
    InvalidParameter,
    ElementAlreadyInList,
    PathNotFound,
    PathNoVertices,
    PathNotRunning,
    PathNotPaused,
    PathNodeAlreadyInList,
    PathNodeNotInList,
    DataNeeded,
    NoDataNeeded,
    DataReady,
    NoDataReady,
    InsufficientMemory,
    Cancelled,
    UnknownBankID,
    BankReadError,
    InvalidSwitchType,
    FormatNotReady,
    WrongBankVersion,
    FileNotFound,
    DeviceNotReady,
    BankAlreadyLoaded,
    RenderedFX,
    ProcessNeeded,
    ProcessDone,
    MemManagerNotInitialized,
    StreamMgrNotInitialized,
    SSEInstructionsNotSupported,
    Busy,
    UnsupportedChannelConfig,
    PluginMediaNotAvailable,
    MustBeVirtualized,
    CommandTooLarge,
    RejectedByFilter,
    InvalidCustomPlatformName,
    DLLCannotLoad,
    DLLPathNotFound,
    NoJavaVM,
    OpenSLError,
    PluginNotRegistered,
    DataAlignmentError,
    DeviceNotCompatible,
    DuplicateUniqueID,
    InitBankNotLoaded,
    DeviceNotFound,
    PlayingIDNotFound,
    InvalidFloatValue,
    FileFormatMismatch,
    NoDistinctListener,
    ResourceInUse,
    InvalidBankType,
    AlreadyInitialized,
    NotInitialized,
    FilePermissionError,
    UnknownFileError,
    TooManyConcurrentOperations,
    InvalidFileSize,
    Deferred,
    FilePathTooLong,
    InvalidState,
};

pub inline fn handleAkResult(result: c.AKRESULT) WwiseError!void {
    return switch (result) {
        c.AK_NotImplemented => return WwiseError.NotImplemented,
        c.AK_Success => return,
        c.AK_Fail => return WwiseError.Fail,
        c.AK_PartialSuccess => return WwiseError.PartialSuccess,
        c.AK_NotCompatible => return WwiseError.NotCompatible,
        c.AK_AlreadyConnected => return WwiseError.AlreadyConnected,
        c.AK_InvalidFile => return WwiseError.InvalidFile,
        c.AK_AudioFileHeaderTooLarge => return WwiseError.AudioFileHeaderTooLarge,
        c.AK_MaxReached => return WwiseError.MaxReached,
        c.AK_InvalidID => return WwiseError.InvalidID,
        c.AK_IDNotFound => return WwiseError.IDNotFound,
        c.AK_InvalidInstanceID => return WwiseError.InvalidInstanceID,
        c.AK_NoMoreData => return WwiseError.NoMoreData,
        c.AK_InvalidStateGroup => return WwiseError.InvalidStateGroup,
        c.AK_ChildAlreadyHasAParent => return WwiseError.ChildAlreadyHasAParent,
        c.AK_InvalidLanguage => return WwiseError.InvalidLanguage,
        c.AK_CannotAddItselfAsAChild => return WwiseError.CannotAddItselfAsAChild,
        c.AK_InvalidParameter => return WwiseError.InvalidParameter,
        c.AK_ElementAlreadyInList => return WwiseError.ElementAlreadyInList,
        c.AK_PathNotFound => return WwiseError.PathNotFound,
        c.AK_PathNoVertices => return WwiseError.PathNoVertices,
        c.AK_PathNotRunning => return WwiseError.PathNotRunning,
        c.AK_PathNotPaused => return WwiseError.PathNotPaused,
        c.AK_PathNodeAlreadyInList => return WwiseError.PathNodeAlreadyInList,
        c.AK_PathNodeNotInList => return WwiseError.PathNodeNotInList,
        c.AK_DataNeeded => return WwiseError.DataNeeded,
        c.AK_NoDataNeeded => return WwiseError.NoDataNeeded,
        c.AK_DataReady => return WwiseError.DataReady,
        c.AK_NoDataReady => return WwiseError.NoDataReady,
        c.AK_InsufficientMemory => return WwiseError.InsufficientMemory,
        c.AK_Cancelled => return WwiseError.Cancelled,
        c.AK_UnknownBankID => return WwiseError.UnknownBankID,
        c.AK_BankReadError => return WwiseError.BankReadError,
        c.AK_InvalidSwitchType => return WwiseError.InvalidSwitchType,
        c.AK_FormatNotReady => return WwiseError.FormatNotReady,
        c.AK_WrongBankVersion => return WwiseError.WrongBankVersion,
        c.AK_FileNotFound => return WwiseError.FileNotFound,
        c.AK_DeviceNotReady => return WwiseError.DeviceNotReady,
        c.AK_BankAlreadyLoaded => return WwiseError.BankAlreadyLoaded,
        c.AK_RenderedFX => return WwiseError.RenderedFX,
        c.AK_ProcessNeeded => return WwiseError.ProcessNeeded,
        c.AK_ProcessDone => return WwiseError.ProcessDone,
        c.AK_MemManagerNotInitialized => return WwiseError.MemManagerNotInitialized,
        c.AK_StreamMgrNotInitialized => return WwiseError.StreamMgrNotInitialized,
        c.AK_SSEInstructionsNotSupported => return WwiseError.SSEInstructionsNotSupported,
        c.AK_Busy => return WwiseError.Busy,
        c.AK_UnsupportedChannelConfig => return WwiseError.UnsupportedChannelConfig,
        c.AK_PluginMediaNotAvailable => return WwiseError.PluginMediaNotAvailable,
        c.AK_MustBeVirtualized => return WwiseError.MustBeVirtualized,
        c.AK_CommandTooLarge => return WwiseError.CommandTooLarge,
        c.AK_RejectedByFilter => return WwiseError.RejectedByFilter,
        c.AK_InvalidCustomPlatformName => return WwiseError.InvalidCustomPlatformName,
        c.AK_DLLCannotLoad => return WwiseError.DLLCannotLoad,
        c.AK_DLLPathNotFound => return WwiseError.DLLPathNotFound,
        c.AK_NoJavaVM => return WwiseError.NoJavaVM,
        c.AK_OpenSLError => return WwiseError.OpenSLError,
        c.AK_PluginNotRegistered => return WwiseError.PluginNotRegistered,
        c.AK_DataAlignmentError => return WwiseError.DataAlignmentError,
        c.AK_DeviceNotCompatible => return WwiseError.DeviceNotCompatible,
        c.AK_DuplicateUniqueID => return WwiseError.DuplicateUniqueID,
        c.AK_InitBankNotLoaded => return WwiseError.InitBankNotLoaded,
        c.AK_DeviceNotFound => return WwiseError.DeviceNotFound,
        c.AK_PlayingIDNotFound => return WwiseError.PlayingIDNotFound,
        c.AK_InvalidFloatValue => return WwiseError.InvalidFloatValue,
        c.AK_FileFormatMismatch => return WwiseError.FileFormatMismatch,
        c.AK_NoDistinctListener => return WwiseError.NoDistinctListener,
        c.AK_ResourceInUse => return WwiseError.ResourceInUse,
        c.AK_InvalidBankType => return WwiseError.InvalidBankType,
        c.AK_AlreadyInitialized => return WwiseError.AlreadyInitialized,
        c.AK_NotInitialized => return WwiseError.NotInitialized,
        c.AK_FilePermissionError => return WwiseError.FilePermissionError,
        c.AK_UnknownFileError => return WwiseError.UnknownFileError,
        else => return WwiseError.NotImplemented,
    };
}

pub const DefaultEnumType = switch (builtin.abi) {
    .msvc => i32,
    else => u32,
};
